### ISSUE TITLE
Please publish latest changes on npm

### ISSUE THREAD

**Issue by bifrost** [DickyT/react-native-textinput-utils#12]

**Comment by leomar-developer** [comment]
I'm seeing this problem too, when comparing the code that gets installed by NPM I can confirm (at least) the index.ios.js file is different than the one shown in github, the code that gets installed by NPM gives an error in react-native because it uses ReactNative.Component instead of React.Component.

**Comment by evollu** [comment]
@DickyT can you publish it

**Comment by DickyT** [comment]
done
